nation_dict = {
    'france': '法国',
    'usa': '美国',
    'uk': '英国',
    'italy': '意大利',
    'japan': '日本',
    'germany': '德国',
    'canada': '加拿大',
    'spain': '西班牙',
    'netherlands': '荷兰',
    'australia': '澳大利亚',
    'korea': '韩国',
    'sweden': '瑞典',
    'austria': '奥地利',
    'china': '中国',
    'croatia': '克罗地亚',
    'denmark': '丹麦'
}

brand_dict = {
    'Abarth': '阿巴斯',
    'Acura': '讴歌',
    'Alpha Romeo': '阿尔法·罗密欧',
    'Alumi Craft': '铝工艺',
    'Aston Martin': '阿斯顿马丁',
    'Audi': '奥迪',
    'Bentley': '宾利',
    'BMW': '宝马',
    'Bugatti': '布加迪',
    'Buick': '别克',
    'Cadillac': '凯迪拉克',
    'Chevrolet': '雪佛兰',
    'Dodge': '道奇',
    'Ferrari': '法拉利',
    'Fiat': '菲亚特',
    'Ford': '福特',
    'Honda': '本田',
    'Hot Wheels': '风火轮',
    'Hotwheels': '风火轮',
    'HotWheels': '风火轮',
    'HUMMER': '悍马',
    'Hummer': '悍马',
    'Hyundai': '现代',
    'Infiniti': '英菲尼迪',
    'Jaguar': '捷豹',
    'Koenigsegg': '柯尼塞格',
    'Lamborghini': '兰博基尼',
    'Lancia': '蓝旗亚',
    'Land Rover': '路虎',
    'Lotus': '路特斯',
    'Maserati': '玛莎拉蒂',
    'Mazda': '马自达',
    'McLaren': '迈凯伦',
    'Mercedes-AMG': '梅赛德斯-AMG',
    'Mercedes-Benz': '梅赛德斯-奔驰',
    'MG': '名爵',
    'Mitsubishi': '三菱',
    'Nissan': '日产',
    'Opel': '欧宝',
    'Pagani': '帕加尼',
    'Peugeot': '标致',
    'Polaris': '北极星',
    'Pontiac': '庞蒂克',
    'Porsche': '保时捷',
    'Renault': '雷诺',
    'Saleen': '赛麟',
    'Subaru': '斯巴鲁',
    'Toyota': '丰田',
    'Vauxhall': '沃克斯豪尔',
    'Volkswagen': '大众',
    'Volvo': '沃尔沃',
    'Czinger': '切格',
    'Lincoln': '林肯'
}

transmission_dict = {
    'RWD': '后轮驱动',
    'FWD': '前轮驱动',
    'AWD': '全轮驱动'
}
